### ISSUE TITLE
Include tag fails when rendering collection page

### ISSUE THREAD

**Issue by maiertech** [octopress/include-tag#1]
Check out `issue` branch from https://github.com/UNStats/UNStats-theme/tree/issue. Execute `bundle` and then

```
bundle exec rake test:preview
```

Source code for test site is in `test/source`. 

In source code I have a page `index.html` (rendered page: http://localhost:4000/) and a collection item `_global_nav/home.html` that renders to `/home/index.html` (rendered page: http://localhost:4000/home/index.html).

They should render exactly the same thing, but in `/home/index.html` the first include got lost.

I'm suspecting your include-tag, but have not had time to debug and verify.

**Comment by imathis** [comment]
Thanks for posting this. I'll look into it today.

**Comment by maiertech** [comment]
I am really not sure what's going on here since I don't understand how Jekyll renders includes and how you tap into the rendering process. If you compare the rendered files you will see that there is a couple of more differences in the rendered files, e.g. some `<p>` tags are missing.

**Comment by imathis** [comment]
That's very interesting indeed. Can you give me steps to see the differences in a specific file? I'll try to update the tests for this tag to match that scenario and be sure I'm getting the correct output.

**Comment by maiertech** [comment]
I just pushed to `issue` branch to make more clear whats going wrong. Please git fetch. The background: I wanna generate the global navigation from a collection and the landing page for each menu item should be the rendered collection page.

`index.md` in `test/source` is my original homepage, which was supposed to be replaced with the collection page `_global_nav/home.md`. The rendered version of both should be identical. But they are not.

In order to allow comparison of rendered pages, I render the `home.md` collection page to `/home/index.html` so you can diff compare it with `/index.html`.

**Comment by maiertech** [comment]
I am not sure if the culprit is your include tag or Jekyll's to which your plugin seems to hand over if the include to be rendered is not from the theme. In my example the includes are from the theme.

**Comment by imathis** [comment]
Alright. I've brought in the Octopress Debugger on this one so I could see what Liquid can see. I added a debugger to the hero_unit include, so now it looks like this:

```
{% if site.hero_unit %}
  {% for item in site.hero_unit %}
    {% debug %}
    {{ item.output }}
  {% endfor %}
{% endif %}
```

When I run `jekyll build` it pulls up the interactive debugger console and I can get access to local variables. So I type `context['item']` and it will show me what the item is in that loop.

Here's a screen shot of my output when it's being run on the `source/_global_nav/home.md` file, notice the collection's output is `nil`:

![home md](https://cloud.githubusercontent.com/assets/12732/6386363/f63d6b44-bd3c-11e4-8905-2931e074461b.png)

Now if I type `continue`, it will go to the next time the debugger is called, which is from the layout being rendered by your `source/index.md` file. Here's what I get:

![index md](https://cloud.githubusercontent.com/assets/12732/6386401/6efa2234-bd3d-11e4-883e-2db4876f75f8.png)

As you can see, this time, the collection's output is rendered properly.

I also checked site posts from the collection and `context.registers[:site].posts.first.output` returns `nil`. But when run during the render of the `index.md` page, it returns the rendered output.

Looking at this, I really don't think this has anything to do with the include tag. I believe this is how the Jekyll rendering pipeline works. I noticed that in your `_config.yml`, the `hero_unit` collection has been set to `output: false`. I believe this has the effect that Jekyll doesn't render it along with the other collections. This means that when a collection tries to reference the output it isn't there yet. By the time the regular pages hit the pipeline, Jekyll has rendered the documents in collections with `output: false`.

I'm not sure why this is the case. It may be that you can open a ticket with the Jekyll folks and get somewhere with this. Though I suggest making a vanilla Jekyll test case that proves this is happening.

**Comment by maiertech** [comment]
Ouch, I'm sorry to create all the work for you. Based on your findings, it occurs to me now that the sequence in which I define my collections matters. If I have a collection A and a collection B and define A before B then if an item of A tries to access a rendered item from B, by this time B has not been rendered yet.

I think this is also the reason why the `<p>` tags in my post excerpts get lost. Post are just another collection and they probably get rendered only after my custom collections.

By changing the sequence in which I define my collections, I get my hero unit back that went missing. But the paras are still lost, because they are part of the posts collection, which I cannot force to be rendered before my collections.

This does not feel right. Jekyll should render on the fly, if needed. I will try to create a simple example and open an issue with the Jekyll project.

Again, sorry for suspecting your include tag and sorry for the workload I caused.

**Comment by imathis** [comment]
Don't worry about it. I learned a thing or two about Jekyll's collections wile messing around with this. Also your use of collections is something I haven't seen before and I find it quite interesting. Using it as a means to auto-populate navigation is interesting, though I'm wondering if that's a bit too clever. You have to make quite a few trips through the template chain to figure out what is going on and the fact that everything is derived from the file system make make it very inflexible as your site grows and you are stuck maintaining these patterns to automate the navigation. I wonder if you wouldn't be better served by adding the navigation as a configuration where it can be easily updated, without having to move a file from one place to another.

Another thing I wondered about, why is the hero_unit a collection instead of an include? The include system was designed for partials, and this is definitely a partial.

**Comment by maiertech** [comment]
Yes, fully aware that my approach might be too clever. I have not decided yet if including rendered collection items in other collection items is very powerful or a just bad idea. I'm learning on the fly here :)

For the hero unit you are right, it's easier to use an include and override that. I need to get used to Octopress ink being very powerful by letting me override stuff in the project to which I apply the theme.
