### ISSUE TITLE
v1.1.2 breaks parameters in includes

### ISSUE THREAD

**Issue by maiertech** [octopress/include-tag#2]
I noticed that v1.1.2 breaks includes with parameters. The includes work, but parameters are `nil` when accessed within the includes. I verified that with v1.1.1 everything works fine.

**Comment by imathis** [comment]
Oof! thanks for the report. I'll see if I can get that fixed.

**Comment by imathis** [comment]
Which version of Jekyll are you using?

**Comment by maiertech** [comment]
Jekyll v2.5.3.

**Comment by imathis** [comment]
[This test passes fine](https://github.com/octopress/include-tag/blob/master/test/includes.html#L14). Are you using vars in a different way? Could you show provide a test case that I can get a failure on?

**Comment by maiertech** [comment]
Can you add a test case where you pass in as parameter a liquid variable and not a string? I have this include:

```
{% include theme:dry/navigation-list.html id="navigation-list" category=category %}
```

In v1.1.2 the `id` gets passed in but the category not, even though it is set.

**Comment by imathis** [comment]
I believe this should be fixed now.

**Comment by maiertech** [comment]
Works. Thanks!
